### ISSUE TITLE
Update from mirror?

### ISSUE THREAD

**Issue by poVoq** [ProfessorKaos64/ftequake#1]
Not sure how this works, but I guess the mirrowing from SF to github is not automatic? Would be nice to have to updated to the latest release :)

**Comment by mdeguzis** [comment]
Oh ok, sure I can do this later today. I don't interact with this repo much anymore, since I use subversion in my build script now. As long as folks want an updated code base, I will.

**Comment by mdeguzis** [comment]
Updated with commit a83b8ca.
